---
name: Setup Rust
description: Setup Rust toolchain and Shipyard registry access
inputs:
  ssh-private-key:
    description: PEM-encoded SSH private key for pulling the Shipyard registry index
    required: true
  token:
    description: Token for pushing to/pulling from the Shipyard registry
    required: true
  registry:
    description: The name of the registry as it appears in the Cargo.toml file
    required: false
    default: wafflehacks
  components:
    description: Comma-separated list of components to be additionally installed
    required: false
runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Add Shipyard host key to .ssh/known_hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan ssh.shipyard.rs >> ~/.ssh/known_hosts

    - name: Login to Shipyard registry
      run: cargo login --registry ${{ inputs.registry }} ${{ inputs.token }}

    - name: Set Cargo environment variables
      run: |
        echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" >> $GITHUB_ENV
        echo "CARGO_HTTP_USER_AGENT=shipyard ${{ inputs.token }}" >> $GITHUB_ENV
