---
name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  registry:
    name: Rust ${{ matrix.rust }} using ${{ matrix.registry }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
        registry:
          - wafflehacks
          - testing
    steps:
      - uses: actions/checkout@v4

      - name: Set registry name
        run: sed -i "s/REGISTRY/${{ matrix.registry }}/g" .cargo/config.toml

      - name: TheHackerApp/setup-rust@main
        uses: ./
        with:
          registry: ${{ matrix.registry }}
          ssh-private-key: ${{ secrets.SHIPYARD_SSH_KEY }}
          token: ${{ secrets.SHIPYARD_TOKEN }}
          toolchain: ${{ matrix.rust }}

      - run: cargo init . --bin --name ci
      - run: cargo add logging --registry ${{ matrix.registry }}
      - run: cargo check

  linker:
    name: Rust ${{ matrix.rust }} with mold linker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4

      - name: Set registry name
        run: sed -i "s/REGISTRY/wafflehacks/g" .cargo/config.toml

      - name: TheHackerApp/setup-rust@main
        uses: ./
        with:
          ssh-private-key: ${{ secrets.SHIPYARD_SSH_KEY }}
          token: ${{ secrets.SHIPYARD_TOKEN }}
          toolchain: ${{ matrix.rust }}
          with-mold: true

      - run: cargo init . --bin --name ci
      - run: cargo add rand
      - run: cargo check
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: -C link-args=-fuse-ld=mold
